export default {
  data: {
    '1': {
      value: {
        input: {
          required: {
            ckpt_name: [
              [
                'AOM\\AbyssOrangeMix-v1.safetensors',
                'AOM\\AbyssOrangeMix-v2.safetensors',
                'AOM\\AbyssOrangeMix-v3.safetensors',
                'Anime\\Counterfeit-v2.5.safetensors',
                'Anime\\DalcefoPainting-v2.safetensors',
                'Anime\\Dosmix.safetensors',
                'Anime\\Evt-v3.0.safetensors',
                'Anime\\LaoleiStyle-v3.0.safetensors',
                'Anime\\MiaoShouAI.safetensors',
                'Anime\\ModernDisneyStyle.safetensors',
                'Anime\\Ogipote5Half.safetensors',
                'Anime\\Quan.safetensors',
                'Anime\\Refslave-v2.safetensors',
                'Anime\\Torino-v2.0.safetensors',
                'Anime\\Waifu-v1.3.safetensors',
                'Anime\\Yyuu.safetensors',
                'Anime\\cherryBlossomMix_v10.safetensors',
                'Anime\\meinamix_meinaV8.safetensors',
                'Anime\\mindplayerFloralboys_mindplayerFloralboys.ckpt',
                'Anime\\mixPro-v3.safetensors',
                'Anime\\nyanMix_230303Absurd2.safetensors',
                'Anime\\pastelboys2D_v10.safetensors',
                'Anime\\pastelmix.safetensors',
                'Anime\\pretty25DV2_pretty25DV2Pruned.safetensors',
                'Anything\\Anything-v3.0.safetensors',
                'Anything\\Anything-v4.0.safetensors',
                'Anything\\Anything-v4.5.safetensors',
                'CmShota\\CmShotaMix-Unreal.safetensors',
                'CmShota\\CmShotaMix.safetensors',
                'Cornflower\\Cornflower-v4.safetensors',
                'Cornflower\\Cornflower-v5.safetensors',
                'Cornflower\\Cornflower-v6.safetensors',
                'Cornflower\\Cornflower-v7.safetensors',
                'Cornflower\\Cornflower-v8.safetensors',
                'Design\\CafeInstagram.safetensors',
                'Design\\CheeseDaddys.safetensors',
                'Design\\DreamShaper.safetensors',
                'Design\\Nice.safetensors',
                'Design\\NovelFinal-4g.safetensors',
                'Design\\NovelInkPunk.safetensors',
                'Design\\SciFiDiffusion-v10.safetensors',
                'Design\\SynthWavePunk-v2.safetensors',
                'Design\\fkingScifiV2_v21f.safetensors',
                'GF\\3Guofeng3_v32Light.safetensors',
                'GF\\GuoFeng-v1.safetensors',
                'GF\\GuoFeng-v2.safetensors',
                'GF\\GuoFeng-v3.0.safetensors',
                'GF\\GuoFeng-v3.1.safetensors',
                'GF\\GuoFeng-v3.2.safetensors',
                'OpenJourney\\OpenJourney-v1.safetensors',
                'OpenJourney\\OpenJourney-v2.safetensors',
                'OpenJourney\\OpenJourneyRobo-v1.safetensors',
                'Protogen\\Protogen-v22.safetensors',
                'Protogen\\ProtogenInfinity.safetensors',
                'Protogen\\chilloutmix_NiPrunedFp32Fix.safetensors',
                'StableDiffusion\\SD-v1.5.safetensors',
                'StableDiffusion\\SD-v2.0-512.safetensors',
                'StableDiffusion\\SD-v2.0-768.safetensors',
                'StableDiffusion\\SD-v2.1-512.safetensors',
                'StableDiffusion\\SD-v2.1-768.safetensors',
              ],
            ],
          },
        },
        output: ['MODEL', 'CLIP', 'VAE'],
        output_name: ['MODEL', 'CLIP', 'VAE'],
        name: 'CheckpointLoaderSimple',
        description: '',
        category: 'loaders',
        widget: 'CheckpointLoaderSimple',
        fields: { ckpt_name: 'AOM\\AbyssOrangeMix-v2.safetensors' },
      },
      position: { x: -639.0673031693432, y: -35.80146798966638 },
    },
    '2': {
      value: {
        input: { required: { text: ['STRING', { multiline: true }], clip: ['CLIP'] } },
        output: ['CONDITIONING'],
        output_name: ['CONDITIONING'],
        name: 'CLIPTextEncode',
        description: '',
        category: 'conditioning',
        widget: 'CLIPTextEncode',
        fields: { text: 'beautiful mountain scenery' },
      },
      position: { x: -195, y: -390 },
    },
    '3': {
      value: {
        input: { required: { text: ['STRING', { multiline: true }], clip: ['CLIP'] } },
        output: ['CONDITIONING'],
        output_name: ['CONDITIONING'],
        name: 'CLIPTextEncode',
        description: '',
        category: 'conditioning',
        widget: 'CLIPTextEncode',
        fields: { text: 'beautiful mountain scenery' },
      },
      position: { x: -228.70842548794585, y: 272.69055459170556 },
    },
    '4': {
      value: {
        input: {
          required: {
            model: ['MODEL'],
            seed: ['INT', { default: 0, min: 0, max: 18446744073709552000 }],
            steps: ['INT', { default: 20, min: 1, max: 10000 }],
            cfg: ['FLOAT', { default: 8, min: 0, max: 100 }],
            sampler_name: [
              [
                'euler',
                'euler_ancestral',
                'heun',
                'dpm_2',
                'dpm_2_ancestral',
                'lms',
                'dpm_fast',
                'dpm_adaptive',
                'dpmpp_2s_ancestral',
                'dpmpp_sde',
                'dpmpp_2m',
                'ddim',
                'uni_pc',
                'uni_pc_bh2',
              ],
            ],
            scheduler: [['karras', 'normal', 'simple', 'ddim_uniform']],
            positive: ['CONDITIONING'],
            negative: ['CONDITIONING'],
            latent_image: ['LATENT'],
            denoise: ['FLOAT', { default: 1, min: 0, max: 1, step: 0.01 }],
          },
        },
        output: ['LATENT'],
        output_name: ['LATENT'],
        name: 'KSampler',
        description: '',
        category: 'sampling',
        widget: 'KSampler',
        fields: {
          seed: 5265640862507760000,
          steps: 1,
          cfg: 4.38,
          sampler_name: 'dpm_2',
          scheduler: 'normal',
          denoise: 0.61,
        },
      },
      position: { x: 225, y: -300 },
    },
    '5': {
      value: {
        input: { required: { samples: ['LATENT'], vae: ['VAE'] } },
        output: ['IMAGE'],
        output_name: ['IMAGE'],
        name: 'VAEDecode',
        description: '',
        category: 'latent',
        widget: 'VAEDecode',
        fields: {},
      },
      position: { x: 615, y: -345 },
    },
    '7': {
      value: {
        input: {
          required: {
            width: ['INT', { default: 512, min: 64, max: 8192, step: 64 }],
            height: ['INT', { default: 512, min: 64, max: 8192, step: 64 }],
            batch_size: ['INT', { default: 1, min: 1, max: 64 }],
          },
        },
        output: ['LATENT'],
        output_name: ['LATENT'],
        name: 'EmptyLatentImage',
        description: '',
        category: 'latent',
        widget: 'EmptyLatentImage',
        fields: { width: 1534, height: 1352, batch_size: 13 },
      },
      position: { x: -150, y: -15 },
    },
    '9': {
      value: {
        input: { required: { images: ['IMAGE'] }, hidden: { prompt: 'PROMPT', extra_pnginfo: 'EXTRA_PNGINFO' } },
        output: [],
        output_name: [],
        name: 'PreviewImage',
        description: '',
        category: 'image',
        widget: 'PreviewImage',
        fields: {},
        images: [{ filename: 'ComfyUI_00001_.png', subfolder: '', type: 'temp' }],
      },
      position: { x: 975, y: -300 },
    },
  },
  connections: [
    { source: '1', sourceHandle: 'MODEL', target: '4', targetHandle: 'model' },
    { source: '1', sourceHandle: 'CLIP', target: '2', targetHandle: 'clip' },
    { source: '1', sourceHandle: 'CLIP', target: '3', targetHandle: 'clip' },
    { source: '1', sourceHandle: 'VAE', target: '5', targetHandle: 'vae' },
    { source: '4', sourceHandle: 'LATENT', target: '5', targetHandle: 'samples' },
    { source: '7', sourceHandle: 'LATENT', target: '4', targetHandle: 'latent_image' },
    { source: '3', sourceHandle: 'CONDITIONING', target: '4', targetHandle: 'negative' },
    { source: '5', sourceHandle: 'IMAGE', target: '6', targetHandle: 'images' },
    { source: '2', sourceHandle: 'CONDITIONING', target: '4', targetHandle: 'positive' },
    { source: '5', sourceHandle: 'IMAGE', target: '9', targetHandle: 'images' },
  ],
}
